Vagrant.configure("2") do |config|

  config.vm.define "static-site" do |static|
    static.vm.box = "debian/bullseye64"
    static.vm.network "private_network", ip: "192.168.50.4"
    
    static.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
      echo '<html><head><title>Success!</title></head><body>You Vagrantfile is fine if you can see this message.</body></html>' > /var/www/html/index.html
    SHELL
  end

  config.vm.define "dynamic-site" do |dynamic|
    dynamic.vm.box = "debian/bullseye64"
    dynamic.vm.network "private_network", ip: "192.168.50.5"
    
    dynamic.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 php libapache2-mod-php
      echo '<?php echo \"<html><head><title>Site is running PHP version \".phpversion().\"</title></head><body>\"; \$limit = rand(1, 1000); for (\$i=0; \$i<\$limit; \$i++){ echo \"<p>Hello, world!</p>\"; } echo \"</body></html>\"; ?>' > /var/www/html/index.php
    SHELL
  end
end